/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as FifoMigrationAuditRouteImport } from './routes/fifo-migration-audit'
import { Route as LocaisRouteImport } from './routes/locais'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParametrosRouteImport } from './routes/parametros'
import { Route as PlanoDeAcaoRouteImport } from './routes/plano-de-acao'
import { Route as ProducaoRouteImport } from './routes/producao'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as LoginRedefinirSenhaRouteImport } from './routes/login/redefinir-senha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const FifoMigrationAuditRoute = FifoMigrationAuditRouteImport.update({
  id: '/fifo-migration-audit',
  path: '/fifo-migration-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaisRoute = LocaisRouteImport.update({
  id: '/locais',
  path: '/locais',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametrosRoute = ParametrosRouteImport.update({
  id: '/parametros',
  path: '/parametros',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoDeAcaoRoute = PlanoDeAcaoRouteImport.update({
  id: '/plano-de-acao',
  path: '/plano-de-acao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoRoute = ProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRedefinirSenhaRoute = LoginRedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => LoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/compras': typeof ComprasRoute
  '/despesas': typeof DespesasRoute
  '/estoque': typeof EstoqueRoute
  '/fifo-migration-audit': typeof FifoMigrationAuditRoute
  '/locais': typeof LocaisRoute
  '/login': typeof LoginRouteWithChildren
  '/parametros': typeof ParametrosRoute
  '/plano-de-acao': typeof PlanoDeAcaoRoute
  '/producao': typeof ProducaoRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
  '/login/redefinir-senha': typeof LoginRedefinirSenhaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/compras': typeof ComprasRoute
  '/despesas': typeof DespesasRoute
  '/estoque': typeof EstoqueRoute
  '/fifo-migration-audit': typeof FifoMigrationAuditRoute
  '/locais': typeof LocaisRoute
  '/login': typeof LoginRouteWithChildren
  '/parametros': typeof ParametrosRoute
  '/plano-de-acao': typeof PlanoDeAcaoRoute
  '/producao': typeof ProducaoRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
  '/login/redefinir-senha': typeof LoginRedefinirSenhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/compras': typeof ComprasRoute
  '/despesas': typeof DespesasRoute
  '/estoque': typeof EstoqueRoute
  '/fifo-migration-audit': typeof FifoMigrationAuditRoute
  '/locais': typeof LocaisRoute
  '/login': typeof LoginRouteWithChildren
  '/parametros': typeof ParametrosRoute
  '/plano-de-acao': typeof PlanoDeAcaoRoute
  '/producao': typeof ProducaoRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
  '/login/redefinir-senha': typeof LoginRedefinirSenhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/compras'
    | '/despesas'
    | '/estoque'
    | '/fifo-migration-audit'
    | '/locais'
    | '/login'
    | '/parametros'
    | '/plano-de-acao'
    | '/producao'
    | '/produtos'
    | '/relatorios'
    | '/vendas'
    | '/login/redefinir-senha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categorias'
    | '/compras'
    | '/despesas'
    | '/estoque'
    | '/fifo-migration-audit'
    | '/locais'
    | '/login'
    | '/parametros'
    | '/plano-de-acao'
    | '/producao'
    | '/produtos'
    | '/relatorios'
    | '/vendas'
    | '/login/redefinir-senha'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/compras'
    | '/despesas'
    | '/estoque'
    | '/fifo-migration-audit'
    | '/locais'
    | '/login'
    | '/parametros'
    | '/plano-de-acao'
    | '/producao'
    | '/produtos'
    | '/relatorios'
    | '/vendas'
    | '/login/redefinir-senha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRoute
  ComprasRoute: typeof ComprasRoute
  DespesasRoute: typeof DespesasRoute
  EstoqueRoute: typeof EstoqueRoute
  FifoMigrationAuditRoute: typeof FifoMigrationAuditRoute
  LocaisRoute: typeof LocaisRoute
  LoginRoute: typeof LoginRouteWithChildren
  ParametrosRoute: typeof ParametrosRoute
  PlanoDeAcaoRoute: typeof PlanoDeAcaoRoute
  ProducaoRoute: typeof ProducaoRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fifo-migration-audit': {
      id: '/fifo-migration-audit'
      path: '/fifo-migration-audit'
      fullPath: '/fifo-migration-audit'
      preLoaderRoute: typeof FifoMigrationAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locais': {
      id: '/locais'
      path: '/locais'
      fullPath: '/locais'
      preLoaderRoute: typeof LocaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametros': {
      id: '/parametros'
      path: '/parametros'
      fullPath: '/parametros'
      preLoaderRoute: typeof ParametrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano-de-acao': {
      id: '/plano-de-acao'
      path: '/plano-de-acao'
      fullPath: '/plano-de-acao'
      preLoaderRoute: typeof PlanoDeAcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao': {
      id: '/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/redefinir-senha': {
      id: '/login/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/login/redefinir-senha'
      preLoaderRoute: typeof LoginRedefinirSenhaRouteImport
      parentRoute: typeof LoginRoute
    }
  }
}

interface LoginRouteChildren {
  LoginRedefinirSenhaRoute: typeof LoginRedefinirSenhaRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginRedefinirSenhaRoute: LoginRedefinirSenhaRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRoute,
  ComprasRoute: ComprasRoute,
  DespesasRoute: DespesasRoute,
  EstoqueRoute: EstoqueRoute,
  FifoMigrationAuditRoute: FifoMigrationAuditRoute,
  LocaisRoute: LocaisRoute,
  LoginRoute: LoginRouteWithChildren,
  ParametrosRoute: ParametrosRoute,
  PlanoDeAcaoRoute: PlanoDeAcaoRoute,
  ProducaoRoute: ProducaoRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
